cache:
  yarn: true
  directories:
    - node_modules
language: node_js
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
node_js:
  - "5.7"
install:
  - gem uninstall bundler
  - gem install bundler --version '1.12'
before_script:
  - nvm install 6.9.1
  - nvm use 6.9.1
  - yarn
script:
  - npm run lint
  - npm run build
