cache:
  yarn: true
  directories:
    - node_modules
language: node_js
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
node_js:
  - "6.9"
install:
  - gem uninstall bundler
  - gem install bundler --version '1.12'
  - yarn
script:
  - npm run lint
  - npm run build
  - npm run styleguide:build
