cache:
  yarn: true
  directories:
    - node_modules
    - test/backstop_data
language: node_js
sudo: false
node_js:
  - '6.9'
install:
  - gem install bundler --version '1.12'
  - yarn
  - npm install -g phantomjs-prebuilt casperjs backstopjs
script:
  - npm run styleguide:build
  - npm run checks
