cache:
  yarn: true
  directories:
    - node_modules
    - test/backstop_data
language: node_js
sudo: false
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
node_js:
  - "11.10.1"
install:
  - yarn
script:
  - npm run styleguide:build
  - npm run checks
